name: SimplePlayerPortals
main: org.simplemc.simpleplayerportals.SimplePlayerPortals
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/SimpleMC/SimplePlayerPortals
author: tajobe
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
